spring:

  datasource:
    url: jdbc:mysql://125.69.76.147:8522/epay?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456

  redis:
    database: 0
    host: 192.168.0.108
    port: 6379
    password: epay

