spring:

  datasource:
    url: jdbc:mysql://localhost:3306/xiaoshu?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 730730

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl